services:
  - type: web
    name: newsphere
    runtime: node
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: NEWS_API_KEY
        sync: false
      - key: GNEWS_API_KEY
        sync: false
      - key: NEWSDATA_API_KEY
        sync: false
      - key: ALLOWED_ORIGIN
        sync: false
