services:
  - type: web
    name: newsphere
    runtime: node
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: NEWS_API_KEY
        value: 491137428012415691283ddf732a8638
      - key: GNEWS_API_KEY
        value: 85b98c11431c80d38c3a665779a8ed3bd
      - key: NEWSDATA_API_KEY
        value: pub_5409ce61ae184f548ee6fbe677772b5f
      - key: ALLOWED_ORIGIN
        value: https://newsphere.onrender.com
